### PR TITLE
fix: detect enum value changes in deepObject parameter properties

### LINKED ISSUE #861: Breaking changes not detected for enum values in deepObject parameter properties and their response schemas
`oasdiff breaking` does not detect enum value removals in two related scenarios:

1. **Request**: enum value removed from a `style: deepObject` query parameter property — neither `request-parameter-enum-value-removed` nor `request-property-enum-value-removed` fires
2. **Response**: enum value removed from a response property — `response-property-enum-value-removed` does not fire

`oasdiff diff` correctly identifies both changes, but the breaking checker has no rules that fire.

The request side is the same class of gap as #567 (type changes in parameter properties, fixed in PR #570), but for enum values.

## Reproduction

`old.yaml`:
```yaml
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      parameters:
        - in: query
          name: filter
          style: deepObject
          schema:
            type: object
            properties:
              origin:
                type: string
                enum:
                  - value-a
                  - value-b
                  - value-c
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    enum:
                      - value-a
                      - value-b
                      - value-c
```

`new.yaml` — same but `value-b` replaced with `value-d` in both enums:
```yaml
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      parameters:
        - in: query
          name: filter
          style: deepObject
          schema:
            type: object
            properties:
              origin:
                type: string
                enum:
                  - value-a
                  - value-d
                  - value-c
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    enum:
                      - value-a
                      - value-d
                      - value-c
```

## Expected

```
error   [request-parameter-enum-value-removed]  removed enum value 'value-b' from query parameter 'filter' property 'origin'
info    [response-property-enum-value-removed]   removed enum value 'value-b' from response property 'origin'
warning [response-property-enum-value-added]     added enum value 'value-d' to response property 'origin'
```

## Actual

Only the response addition warning fires:

```
1 changes: 0 error, 1 warning, 0 info
warning [response-property-enum-value-added] added 'value-d' to 'origin' response property
```

Both removals are silently missed.

## Proof that diff sees both

`oasdiff diff old.yaml new.yaml` correctly shows:

```
parameters > query > filter > schema > properties > origin > enum > deleted: value-b
responses > 200 > application/json > schema > properties > origin > enum > deleted: value-b
```

## Proof that non-deepObject parameters work

If `origin` is a top-level query parameter (not a deepObject property), `request-parameter-enum-value-removed` fires correctly:

```
2 changes: 1 error, 1 warning, 0 info
error [request-parameter-enum-value-removed] removed the enum value 'value-b' from the 'query' request parameter 'origin'
```

## Impact

Removing an enum value from a deepObject filter parameter is a breaking change — clients sending that filter value will get validation errors. This silently passes CI.

## Version

Reproduced on v1.10.23 and v1.14.0.

### PR DESCRIPTION
**Pull request by BobbyBorisov**
## Summary

Adds breaking change detection for enum values added/removed from properties within object-typed request parameters (`style: deepObject`).

Previously, only top-level parameter enums were checked by `request-parameter-enum-value-removed`. Properties nested inside a parameter's object schema were silently skipped because the checker returned early when the parameter itself had no enum.

This is the same class of gap as #567 (fixed in PR #570 for type changes) but for enum values.

## New check IDs

- `request-parameter-property-enum-value-removed` (ERR) — removing an enum value from a deepObject parameter property is a breaking change
- `request-parameter-property-enum-value-added` (INFO) — adding an enum value to a deepObject parameter property

## Root cause

The `if enumDiff == nil { continue }` guard in `RequestParameterEnumValueUpdatedCheck` skipped the entire parameter (including its nested properties) when the parameter's top-level schema had no enum. For `style: deepObject` parameters with `type: object`, the enum lives on the properties, not the parameter itself.

## Fix

- Changed the early `continue` to a conditional block so property traversal always runs
- Added `CheckModifiedPropertiesDiff()` to traverse parameter schema properties (same pattern as PR #570)
- Added localization messages in all 4 languages (en, es, pt-br, ru)
- Added tests with deepObject parameter test data

## Before / After

**Before** — enum removal in deepObject parameter property not detected:
```
1 changes: 0 error, 1 warning, 0 info
warning [response-property-enum-value-added] added 'value-d' to response property
```

**After** — correctly flagged as error:
```
2 changes: 1 error, 1 warning, 0 info
error   [request-parameter-property-enum-value-removed] removed the enum value `value-b`
        from the property `origin` of the `query` request parameter `filter`
warning [response-property-enum-value-added] added `value-d` to response property
```

Fixes #861

### CODE REVIEW

File: checker/check_request_parameter_enum_value_updated.go [hunk 1]
```diff
@@ -7,8 +7,10 @@ import (
 )
 
 const (
-	RequestParameterEnumValueAddedId   = "request-parameter-enum-value-added"
-	RequestParameterEnumValueRemovedId = "request-parameter-enum-value-removed"
+	RequestParameterEnumValueAddedId            = "request-parameter-enum-value-added"
+	RequestParameterEnumValueRemovedId          = "request-parameter-enum-value-removed"
+	RequestParameterPropertyEnumValueAddedId    = "request-parameter-property-enum-value-added"
+	RequestParameterPropertyEnumValueRemovedId  = "request-parameter-property-enum-value-removed"
```
Comment (reuvenharrison) [inline checker/check_request_parameter_enum_value_updated.go]: This fails the `git diff --exit-code` check in CI because the const block needs reformatting. Run `make lint` locally before pushing to catch this (and any `go vet` / `golangci-lint` issues). One-click fix for this one:

```suggestion
	RequestParameterEnumValueAddedId           = "request-parameter-enum-value-added"
	RequestParameterEnumValueRemovedId         = "request-parameter-enum-value-removed"
	RequestParameterPropertyEnumValueAddedId   = "request-parameter-property-enum-value-added"
	RequestParameterPropertyEnumValueRemovedId = "request-parameter-property-enum-value-removed"
```

**Review by reuvenharrison — COMMENTED** [review]
Nice targeted fix, follows the #570 pattern cleanly. Thanks for the localization coverage and the message test.

A few non-blocking notes for follow-up:

**1. Helper extraction.** The top-level enum block and the new property enum block are near-mirror copies. Worth extracting into a private helper parameterized by the ID pair and args builder. Reference pattern: `checker/check_response_status_updated.go:56`. `responseStatusUpdated` takes an `id string` and serves both `ResponseSuccessStatusUpdatedCheck` and `ResponseNonSuccessStatusUpdatedCheck` via a filter function. Your case would pass both ID pairs since they're unrelated names. Happy to see as a follow-up PR.

**2. Test filename convention.** `check_request_parameter_property_enum_value_updated_test.go` reads as if there's a matching source file, but the check logic lives in `check_request_parameter_enum_value_updated.go`. By project convention, test files mirror the source file name. Consider merging this test into `check_request_parameter_enum_value_updated_test.go`.

**3. Test-reuse readability.** `TestRequestParameterPropertyEnumValueAddedCheck` swaps base/revision fixtures to exercise the "added" path using the same data files. Clever, but a one-line comment would help future readers:

```go
// Swap base/revision to exercise the added-value path using the same fixtures.
```

**Comment by BobbyBorisov** [comment]
Thanks for the review! All three suggestions applied in df38872:

1. **Helper extraction** — Extracted `checkParameterEnumDiff` helper parameterized by ID pair and args builder, following the `check_response_status_updated.go` pattern.
2. **Test consolidation** — Merged property enum tests into `check_request_parameter_enum_value_updated_test.go` and deleted the separate file.
3. **Test comment** — Added comment explaining the swap base/revision technique.

**Comment by reuvenharrison** [comment]
Merged a fix for the dead Slack link that was failing the `detect-broken-links` check (#863). Please rebase on main so the fix lands on this branch:

```
git fetch origin
git rebase origin/main
git push --force-with-lease
```

Once CI is green I will approve and merge. Thanks for the quick turnaround on the review feedback.

**Comment by BobbyBorisov** [comment]
Thanks for the quick review! 🚀 I just rebased on main.

**Review by reuvenharrison — APPROVED** [review]
